#!/usr/bin/env python3
"""
Train one XGBoost model per F1 telemetry channel.

Default input is the balanced relabeled dataset generated by:
  scripts/relabel_f1_exact_algorithms_v2.py

Strict mode:
  - requires `best_algorithm_v2`
  - requires `channel`
  - no fallback to legacy labels
"""

from __future__ import annotations

import json
import time
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd
import xgboost as xgb
from sklearn.metrics import accuracy_score, balanced_accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

SCRIPT_DIR = Path(__file__).resolve().parent
ROOT = SCRIPT_DIR.parent

DATA_CSV = Path(
    "/Volumes/k/thesis_data/f1_only_1m_packed/training_dataset_algos_v2_hard_m0p05_balanced.csv"
)
INDEX_CSV = Path("/Volumes/k/thesis_data/f1_only_1m_packed/index.csv")
MODEL_ROOT = ROOT / "models" / "xgboost_v5_f1_per_channel"
RESULTS_ROOT = ROOT / "results" / "xgboost_v5_f1_per_channel"
PREPARED_ROOT = RESULTS_ROOT / "prepared_datasets"

SEED = 42
MAX_RATIO_PER_CHANNEL = 3.0
MIN_CLASS_COUNT_FOR_SPLIT = 3
MIN_WINNER_MARGIN = 0.0

XGB_PARAMS = dict(
    n_estimators=500,
    max_depth=7,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,
    reg_alpha=0.1,
    reg_lambda=1.0,
    random_state=SEED,
    n_jobs=-1,
    tree_method="hist",
    objective="multi:softprob",
    eval_metric="mlogloss",
)


def compute_sample_weights(y: np.ndarray) -> np.ndarray:
    classes, counts = np.unique(y, return_counts=True)
    total = len(y)
    weight_map = {c: total / (len(classes) * cnt) for c, cnt in zip(classes, counts)}
    return np.array([weight_map[yi] for yi in y], dtype=np.float64)


def balanced_undersample(
    df: pd.DataFrame,
    label_col: str,
    max_ratio: float = MAX_RATIO_PER_CHANNEL,
    random_state: int = SEED,
) -> pd.DataFrame:
    counts = df[label_col].value_counts()
    if counts.empty:
        return df
    min_count = int(counts.min())
    cap = max(1, int(min_count * max_ratio))
    parts = []
    for cls, subset in df.groupby(label_col):
        n = min(len(subset), cap)
        parts.append(subset.sample(n=n, random_state=random_state))
    return (
        pd.concat(parts, ignore_index=True)
        .sample(frac=1.0, random_state=random_state)
        .reset_index(drop=True)
    )


def resolve_feature_columns(df: pd.DataFrame, label_col: str) -> list[str]:
    banned = {
        label_col,
        "best_algorithm",
        "best_algorithm_v2",
        "winner_margin_v2",
        "array_id",
        "file",
        "event",
        "session",
        "driver",
        "lap",
        "channel",
        "dtype",
        "year",
        "round",
    }
    feature_cols: list[str] = []
    for col in df.columns:
        if col in banned:
            continue
        if col.startswith("time_"):
            continue
        if pd.api.types.is_numeric_dtype(df[col]):
            feature_cols.append(col)
    if not feature_cols:
        raise ValueError("No numeric feature columns found for training.")
    return feature_cols


def train_one_channel(
    ch: str,
    ch_df: pd.DataFrame,
    feature_cols: list[str],
    label_col: str,
) -> dict:
    rows_raw = int(len(ch_df))
    if "winner_margin_v2" in ch_df.columns:
        ch_df = ch_df[ch_df["winner_margin_v2"] >= MIN_WINNER_MARGIN].copy()
    rows_after_margin = int(len(ch_df))

    original_counts = ch_df[label_col].value_counts()
    keep_classes = original_counts[original_counts >= MIN_CLASS_COUNT_FOR_SPLIT].index.tolist()
    dropped_classes = sorted(set(original_counts.index.tolist()) - set(keep_classes))
    if keep_classes:
        ch_df = ch_df[ch_df[label_col].isin(keep_classes)].copy()
    rows_after_drop = int(len(ch_df))

    ch_df = balanced_undersample(ch_df, label_col=label_col, max_ratio=MAX_RATIO_PER_CHANNEL)
    rows_after_balance = int(len(ch_df))
    classes = sorted(ch_df[label_col].dropna().unique().tolist())
    if len(classes) < 2:
        return {
            "channel": ch,
            "status": "skipped",
            "reason": (
                "need >=2 classes after rare-class dropping; "
                f"found {classes}, dropped={dropped_classes}"
            ),
            "rows": int(len(ch_df)),
            "rows_raw": rows_raw,
            "rows_after_margin": rows_after_margin,
            "rows_after_drop": rows_after_drop,
            "rows_after_balance": rows_after_balance,
            "class_counts_before_drop": {k: int(v) for k, v in original_counts.to_dict().items()},
        }

    class_counts = ch_df[label_col].value_counts()
    min_count = int(class_counts.min())
    if min_count < MIN_CLASS_COUNT_FOR_SPLIT:
        return {
            "channel": ch,
            "status": "skipped",
            "reason": (
                "insufficient per-class samples for stratified 70/15/15 split "
                f"(min class count={min_count})"
            ),
            "rows": int(len(ch_df)),
            "rows_raw": rows_raw,
            "rows_after_margin": rows_after_margin,
            "rows_after_drop": rows_after_drop,
            "rows_after_balance": rows_after_balance,
            "class_counts": {k: int(v) for k, v in class_counts.to_dict().items()},
        }

    train_df, temp_df = train_test_split(
        ch_df, test_size=0.30, stratify=ch_df[label_col], random_state=SEED
    )
    val_df, test_df = train_test_split(
        temp_df, test_size=0.50, stratify=temp_df[label_col], random_state=SEED
    )

    X_train = train_df[feature_cols].values
    y_train = train_df[label_col].values
    X_val = val_df[feature_cols].values
    y_val = val_df[label_col].values
    X_test = test_df[feature_cols].values
    y_test = test_df[label_col].values

    le = LabelEncoder().fit(classes)
    y_train_enc = le.transform(y_train)
    y_val_enc = le.transform(y_val)
    y_test_enc = le.transform(y_test)

    params = dict(XGB_PARAMS)
    params["num_class"] = len(classes)
    model = xgb.XGBClassifier(**params)
    model.fit(
        X_train,
        y_train_enc,
        sample_weight=compute_sample_weights(y_train_enc),
        eval_set=[(X_train, y_train_enc), (X_val, y_val_enc)],
        verbose=False,
    )

    def eval_split(X, y_true, y_true_enc):
        y_pred_enc = model.predict(X)
        y_pred = le.inverse_transform(y_pred_enc)
        return dict(
            accuracy=float(accuracy_score(y_true, y_pred)),
            balanced_accuracy=float(balanced_accuracy_score(y_true, y_pred)),
            confusion_matrix=confusion_matrix(y_true, y_pred, labels=classes).tolist(),
            classification_report=classification_report(
                y_true, y_pred, labels=classes, output_dict=True, zero_division=0
            ),
            n_rows=int(len(y_true_enc)),
        )

    ch_model_dir = MODEL_ROOT / ch
    ch_results_dir = RESULTS_ROOT / ch
    ch_prepared_dir = PREPARED_ROOT / ch
    ch_model_dir.mkdir(parents=True, exist_ok=True)
    ch_results_dir.mkdir(parents=True, exist_ok=True)
    ch_prepared_dir.mkdir(parents=True, exist_ok=True)

    model_path = ch_model_dir / "xgb_model.json"
    model.get_booster().save_model(str(model_path))
    ch_df.to_csv(ch_prepared_dir / "training_input_balanced.csv", index=False)

    results = {
        "channel": ch,
        "status": "trained",
        "classes": classes,
        "rows_total": int(len(ch_df)),
        "rows_raw": rows_raw,
        "rows_after_margin": rows_after_margin,
        "rows_after_drop": rows_after_drop,
        "rows_after_balance": rows_after_balance,
        "rows_train": int(len(train_df)),
        "rows_val": int(len(val_df)),
        "rows_test": int(len(test_df)),
        "metrics": {
            "train": eval_split(X_train, y_train, y_train_enc),
            "val": eval_split(X_val, y_val, y_val_enc),
            "test": eval_split(X_test, y_test, y_test_enc),
        },
        "feature_columns": feature_cols,
        "xgb_params": params,
        "channel_balance_max_ratio": MAX_RATIO_PER_CHANNEL,
        "min_winner_margin": MIN_WINNER_MARGIN,
        "dropped_rare_classes": dropped_classes,
        "class_counts_before_drop": {k: int(v) for k, v in original_counts.to_dict().items()},
        "class_counts_after_drop": {
            k: int(v) for k, v in ch_df[label_col].value_counts().to_dict().items()
        },
        "model_path": str(model_path),
    }

    (ch_results_dir / "evaluation_results.json").write_text(json.dumps(results, indent=2))
    pred = pd.DataFrame(
        {
            "actual": y_test,
            "predicted": le.inverse_transform(model.predict(X_test)),
        }
    )
    pred.to_csv(ch_results_dir / "predictions_test.csv", index=False)
    return results


def main() -> None:
    print("=" * 80)
    print("XGBOOST v5 F1 PER-CHANNEL")
    print("=" * 80)
    print(f"Input: {DATA_CSV}")

    if not DATA_CSV.exists():
        raise SystemExit(f"Dataset not found: {DATA_CSV}")

    MODEL_ROOT.mkdir(parents=True, exist_ok=True)
    RESULTS_ROOT.mkdir(parents=True, exist_ok=True)
    PREPARED_ROOT.mkdir(parents=True, exist_ok=True)

    start = time.time()
    df = pd.read_csv(DATA_CSV)
    if "channel" not in df.columns:
        if not INDEX_CSV.exists():
            raise SystemExit(
                "Dataset missing 'channel' and index file not found for recovery: "
                f"{INDEX_CSV}"
            )
        idx = pd.read_csv(INDEX_CSV, usecols=["file", "channel"])
        df = df.merge(idx, on="file", how="left", validate="many_to_one")
        missing_ch = int(df["channel"].isna().sum())
        if missing_ch > 0:
            raise SystemExit(
                f"Recovered channel from index.csv, but {missing_ch} rows still missing channel."
            )
        print(f"Recovered channel via index join: {INDEX_CSV}")
    if "best_algorithm_v2" not in df.columns:
        raise SystemExit("Dataset missing required label column: best_algorithm_v2")
    label_col = "best_algorithm_v2"

    df = df[df[label_col].notna()].reset_index(drop=True)
    feature_cols = resolve_feature_columns(df, label_col)

    print(f"Rows: {len(df):,}")
    print(f"Label: {label_col}")
    print(f"Features: {len(feature_cols)}")

    summary = {
        "timestamp": datetime.now().isoformat(),
        "input_csv": str(DATA_CSV),
        "label_col": label_col,
        "feature_columns": feature_cols,
        "min_winner_margin": MIN_WINNER_MARGIN,
        "min_class_count_for_split": MIN_CLASS_COUNT_FOR_SPLIT,
        "max_ratio_per_channel": MAX_RATIO_PER_CHANNEL,
        "channels": {},
    }

    channels = sorted(df["channel"].dropna().astype(str).unique().tolist())
    for ch in channels:
        ch_df = df[df["channel"].astype(str) == ch].copy()
        print(f"\n[TRAIN] {ch}: rows={len(ch_df):,}")
        try:
            result = train_one_channel(ch, ch_df, feature_cols, label_col)
        except Exception as e:
            result = {
                "channel": ch,
                "status": "skipped",
                "reason": f"training error: {e}",
                "rows": int(len(ch_df)),
            }
        summary["channels"][ch] = result
        if result["status"] == "trained":
            m = result["metrics"]["test"]
            print(
                f"  test_acc={m['accuracy']:.3f}  test_bal_acc={m['balanced_accuracy']:.3f}"
            )
        else:
            print(f"  skipped: {result['reason']}")

    print("\nSUMMARY TABLE")
    print("channel     status    rows_raw rows_margin rows_bal  test_acc test_bal_acc")
    for ch in channels:
        r = summary["channels"][ch]
        status = r.get("status", "na")
        rr = r.get("rows_raw", r.get("rows", 0))
        rm = r.get("rows_after_margin", 0)
        rb = r.get("rows_after_balance", 0)
        if status == "trained":
            ta = r["metrics"]["test"]["accuracy"]
            tb = r["metrics"]["test"]["balanced_accuracy"]
            print(f"{ch:10s} {status:8s} {rr:8d} {rm:11d} {rb:8d} {ta:8.3f} {tb:12.3f}")
        else:
            print(f"{ch:10s} {status:8s} {rr:8d} {rm:11d} {rb:8d} {'-':>8s} {'-':>12s}")

    summary["elapsed_sec"] = round(time.time() - start, 2)
    (RESULTS_ROOT / "summary.json").write_text(json.dumps(summary, indent=2))
    print(f"\nDone in {summary['elapsed_sec']}s")
    print(f"Models:  {MODEL_ROOT}")
    print(f"Results: {RESULTS_ROOT}")


if __name__ == "__main__":
    main()
